const bcrypt = require("bcryptjs");

module.exports = {
  up: async (queryInterface) => {
    const hashedPassword = await bcrypt.hash("123", 10);

    // 🔹 Insert New Departments
    await queryInterface.bulkInsert("Departments", [
      { name: "Operations", createdAt: new Date(), updatedAt: new Date() },
      {
        name: "Customer Support",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { name: "Legal", createdAt: new Date(), updatedAt: new Date() },
      { name: "Compliance", createdAt: new Date(), updatedAt: new Date() },
      { name: "Engineering", createdAt: new Date(), updatedAt: new Date() },
      { name: "Design", createdAt: new Date(), updatedAt: new Date() },
      { name: "Product", createdAt: new Date(), updatedAt: new Date() },
      { name: "Sales", createdAt: new Date(), updatedAt: new Date() },
      {
        name: "Quality Assurance",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      { name: "Procurement", createdAt: new Date(), updatedAt: new Date() },
    ]);

    // 🔹 Fetch Department IDs
    const departments = await queryInterface.sequelize.query(
      "SELECT id, name FROM Departments;",
      {
        type: queryInterface.sequelize.QueryTypes.SELECT,
      }
    );

    const departmentMap = {};
    departments.forEach((dept) => {
      departmentMap[dept.name] = dept.id;
    });

    // 🔹 Insert New Users
    await queryInterface.bulkInsert("Users", [
      {
        name: "Noah",
        surname: "Davis",
        username: "noahdavis0",
        email: "noahdavis0@example.com",
        password: hashedPassword,
        birthday: "2000-02-08",
        hourlyPay: 18.25,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Garcia",
        username: "isabellagarcia1",
        email: "isabellagarcia1@example.com",
        password: hashedPassword,
        birthday: "1995-12-03",
        hourlyPay: 45.51,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Rodriguez",
        username: "oliviarodriguez2",
        email: "oliviarodriguez2@example.com",
        password: hashedPassword,
        birthday: "1993-12-25",
        hourlyPay: 33.27,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Brown",
        username: "noahbrown3",
        email: "noahbrown3@example.com",
        password: hashedPassword,
        birthday: "1996-11-09",
        hourlyPay: 20.62,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Martinez",
        username: "emmamartinez4",
        email: "emmamartinez4@example.com",
        password: hashedPassword,
        birthday: "1990-05-05",
        hourlyPay: 42.51,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Rodriguez",
        username: "emmarodriguez5",
        email: "emmarodriguez5@example.com",
        password: hashedPassword,
        birthday: "1996-08-18",
        hourlyPay: 42.29,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Rodriguez",
        username: "isabellarodriguez6",
        email: "isabellarodriguez6@example.com",
        password: hashedPassword,
        birthday: "2007-11-22",
        hourlyPay: 48.43,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Smith",
        username: "emmasmith7",
        email: "emmasmith7@example.com",
        password: hashedPassword,
        birthday: "2001-05-09",
        hourlyPay: 42.54,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Davis",
        username: "emmadavis8",
        email: "emmadavis8@example.com",
        password: hashedPassword,
        birthday: "1997-04-25",
        hourlyPay: 48.97,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Smith",
        username: "isabellasmith9",
        email: "isabellasmith9@example.com",
        password: hashedPassword,
        birthday: "2008-11-10",
        hourlyPay: 32.05,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Brown",
        username: "sophiabrown10",
        email: "sophiabrown10@example.com",
        password: hashedPassword,
        birthday: "2003-10-06",
        hourlyPay: 28.62,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Williams",
        username: "isabellawilliams11",
        email: "isabellawilliams11@example.com",
        password: hashedPassword,
        birthday: "1998-04-25",
        hourlyPay: 11.75,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Williams",
        username: "noahwilliams12",
        email: "noahwilliams12@example.com",
        password: hashedPassword,
        birthday: "2005-05-23",
        hourlyPay: 44.43,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Miller",
        username: "avamiller13",
        email: "avamiller13@example.com",
        password: hashedPassword,
        birthday: "1995-12-06",
        hourlyPay: 15.69,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Martinez",
        username: "isabellamartinez14",
        email: "isabellamartinez14@example.com",
        password: hashedPassword,
        birthday: "1992-11-23",
        hourlyPay: 46.51,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Garcia",
        username: "isabellagarcia15",
        email: "isabellagarcia15@example.com",
        password: hashedPassword,
        birthday: "1998-02-04",
        hourlyPay: 23.6,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Davis",
        username: "williamdavis16",
        email: "williamdavis16@example.com",
        password: hashedPassword,
        birthday: "1990-03-16",
        hourlyPay: 45.7,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Garcia",
        username: "liamgarcia17",
        email: "liamgarcia17@example.com",
        password: hashedPassword,
        birthday: "1996-10-14",
        hourlyPay: 27.03,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Johnson",
        username: "sophiajohnson18",
        email: "sophiajohnson18@example.com",
        password: hashedPassword,
        birthday: "2008-12-13",
        hourlyPay: 10.8,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Brown",
        username: "liambrown19",
        email: "liambrown19@example.com",
        password: hashedPassword,
        birthday: "1994-12-18",
        hourlyPay: 42.27,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Jones",
        username: "williamjones20",
        email: "williamjones20@example.com",
        password: hashedPassword,
        birthday: "2003-05-26",
        hourlyPay: 14.6,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Brown",
        username: "liambrown21",
        email: "liambrown21@example.com",
        password: hashedPassword,
        birthday: "2003-05-17",
        hourlyPay: 28.52,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Miller",
        username: "oliviamiller22",
        email: "oliviamiller22@example.com",
        password: hashedPassword,
        birthday: "1998-01-14",
        hourlyPay: 49.36,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Brown",
        username: "avabrown23",
        email: "avabrown23@example.com",
        password: hashedPassword,
        birthday: "2005-06-23",
        hourlyPay: 22.85,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Williams",
        username: "williamwilliams24",
        email: "williamwilliams24@example.com",
        password: hashedPassword,
        birthday: "2000-12-01",
        hourlyPay: 38.21,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Martinez",
        username: "liammartinez25",
        email: "liammartinez25@example.com",
        password: hashedPassword,
        birthday: "2009-06-07",
        hourlyPay: 27.55,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Garcia",
        username: "sophiagarcia26",
        email: "sophiagarcia26@example.com",
        password: hashedPassword,
        birthday: "2004-04-12",
        hourlyPay: 36.4,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Jones",
        username: "williamjones27",
        email: "williamjones27@example.com",
        password: hashedPassword,
        birthday: "2007-05-13",
        hourlyPay: 15.91,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Garcia",
        username: "oliviagarcia28",
        email: "oliviagarcia28@example.com",
        password: hashedPassword,
        birthday: "1990-09-18",
        hourlyPay: 18.61,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Jones",
        username: "williamjones29",
        email: "williamjones29@example.com",
        password: hashedPassword,
        birthday: "1995-11-10",
        hourlyPay: 40.97,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Martinez",
        username: "emmamartinez30",
        email: "emmamartinez30@example.com",
        password: hashedPassword,
        birthday: "1995-12-01",
        hourlyPay: 22.6,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Jones",
        username: "sophiajones31",
        email: "sophiajones31@example.com",
        password: hashedPassword,
        birthday: "2004-10-23",
        hourlyPay: 17.37,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Williams",
        username: "avawilliams32",
        email: "avawilliams32@example.com",
        password: hashedPassword,
        birthday: "2000-04-16",
        hourlyPay: 15.41,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Smith",
        username: "jamessmith33",
        email: "jamessmith33@example.com",
        password: hashedPassword,
        birthday: "1998-12-26",
        hourlyPay: 45.12,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Brown",
        username: "isabellabrown34",
        email: "isabellabrown34@example.com",
        password: hashedPassword,
        birthday: "2003-12-21",
        hourlyPay: 31.62,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Martinez",
        username: "liammartinez35",
        email: "liammartinez35@example.com",
        password: hashedPassword,
        birthday: "1995-03-26",
        hourlyPay: 49.68,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Williams",
        username: "isabellawilliams36",
        email: "isabellawilliams36@example.com",
        password: hashedPassword,
        birthday: "1991-05-14",
        hourlyPay: 35.53,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Rodriguez",
        username: "avarodriguez37",
        email: "avarodriguez37@example.com",
        password: hashedPassword,
        birthday: "2008-09-15",
        hourlyPay: 27.3,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Williams",
        username: "oliviawilliams38",
        email: "oliviawilliams38@example.com",
        password: hashedPassword,
        birthday: "1991-09-14",
        hourlyPay: 41.67,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Rodriguez",
        username: "liamrodriguez39",
        email: "liamrodriguez39@example.com",
        password: hashedPassword,
        birthday: "2000-03-08",
        hourlyPay: 26.87,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Smith",
        username: "williamsmith40",
        email: "williamsmith40@example.com",
        password: hashedPassword,
        birthday: "2009-03-01",
        hourlyPay: 12.78,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Martinez",
        username: "jamesmartinez41",
        email: "jamesmartinez41@example.com",
        password: hashedPassword,
        birthday: "1996-10-10",
        hourlyPay: 34.99,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Smith",
        username: "sophiasmith42",
        email: "sophiasmith42@example.com",
        password: hashedPassword,
        birthday: "2002-06-12",
        hourlyPay: 29.74,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Rodriguez",
        username: "benjaminrodriguez43",
        email: "benjaminrodriguez43@example.com",
        password: hashedPassword,
        birthday: "2001-03-24",
        hourlyPay: 42.35,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Williams",
        username: "isabellawilliams44",
        email: "isabellawilliams44@example.com",
        password: hashedPassword,
        birthday: "1999-03-01",
        hourlyPay: 25.94,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Brown",
        username: "isabellabrown45",
        email: "isabellabrown45@example.com",
        password: hashedPassword,
        birthday: "2003-12-03",
        hourlyPay: 28.59,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Brown",
        username: "sophiabrown46",
        email: "sophiabrown46@example.com",
        password: hashedPassword,
        birthday: "1990-08-03",
        hourlyPay: 37.1,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Brown",
        username: "isabellabrown47",
        email: "isabellabrown47@example.com",
        password: hashedPassword,
        birthday: "1996-07-28",
        hourlyPay: 15.02,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Davis",
        username: "isabelladavis48",
        email: "isabelladavis48@example.com",
        password: hashedPassword,
        birthday: "1998-03-27",
        hourlyPay: 45.76,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Jones",
        username: "noahjones49",
        email: "noahjones49@example.com",
        password: hashedPassword,
        birthday: "2009-01-11",
        hourlyPay: 34.14,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Garcia",
        username: "sophiagarcia50",
        email: "sophiagarcia50@example.com",
        password: hashedPassword,
        birthday: "2003-12-10",
        hourlyPay: 25.9,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Jones",
        username: "liamjones51",
        email: "liamjones51@example.com",
        password: hashedPassword,
        birthday: "1991-07-06",
        hourlyPay: 44.31,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Garcia",
        username: "noahgarcia52",
        email: "noahgarcia52@example.com",
        password: hashedPassword,
        birthday: "2006-12-01",
        hourlyPay: 16.73,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Jones",
        username: "jamesjones53",
        email: "jamesjones53@example.com",
        password: hashedPassword,
        birthday: "1990-04-13",
        hourlyPay: 49.73,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Garcia",
        username: "benjamingarcia54",
        email: "benjamingarcia54@example.com",
        password: hashedPassword,
        birthday: "2005-05-06",
        hourlyPay: 25.89,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Davis",
        username: "emmadavis55",
        email: "emmadavis55@example.com",
        password: hashedPassword,
        birthday: "2001-07-20",
        hourlyPay: 20.42,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Jones",
        username: "benjaminjones56",
        email: "benjaminjones56@example.com",
        password: hashedPassword,
        birthday: "2008-04-19",
        hourlyPay: 12.26,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Brown",
        username: "benjaminbrown57",
        email: "benjaminbrown57@example.com",
        password: hashedPassword,
        birthday: "2007-07-03",
        hourlyPay: 45.85,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Williams",
        username: "emmawilliams58",
        email: "emmawilliams58@example.com",
        password: hashedPassword,
        birthday: "2007-05-17",
        hourlyPay: 10.63,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Smith",
        username: "jamessmith59",
        email: "jamessmith59@example.com",
        password: hashedPassword,
        birthday: "2007-10-19",
        hourlyPay: 33.04,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Brown",
        username: "avabrown60",
        email: "avabrown60@example.com",
        password: hashedPassword,
        birthday: "1993-05-15",
        hourlyPay: 39.99,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Rodriguez",
        username: "noahrodriguez61",
        email: "noahrodriguez61@example.com",
        password: hashedPassword,
        birthday: "1995-03-08",
        hourlyPay: 10.46,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Garcia",
        username: "sophiagarcia62",
        email: "sophiagarcia62@example.com",
        password: hashedPassword,
        birthday: "2009-05-15",
        hourlyPay: 33.87,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Davis",
        username: "noahdavis63",
        email: "noahdavis63@example.com",
        password: hashedPassword,
        birthday: "2004-09-14",
        hourlyPay: 26.92,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Garcia",
        username: "liamgarcia64",
        email: "liamgarcia64@example.com",
        password: hashedPassword,
        birthday: "1993-12-01",
        hourlyPay: 35.83,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Garcia",
        username: "oliviagarcia65",
        email: "oliviagarcia65@example.com",
        password: hashedPassword,
        birthday: "1999-12-22",
        hourlyPay: 43.68,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Jones",
        username: "sophiajones66",
        email: "sophiajones66@example.com",
        password: hashedPassword,
        birthday: "2000-05-21",
        hourlyPay: 29.95,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Rodriguez",
        username: "oliviarodriguez67",
        email: "oliviarodriguez67@example.com",
        password: hashedPassword,
        birthday: "2001-01-16",
        hourlyPay: 22.58,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Davis",
        username: "avadavis68",
        email: "avadavis68@example.com",
        password: hashedPassword,
        birthday: "1997-06-18",
        hourlyPay: 12.73,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Garcia",
        username: "sophiagarcia69",
        email: "sophiagarcia69@example.com",
        password: hashedPassword,
        birthday: "2003-10-11",
        hourlyPay: 26.9,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Smith",
        username: "jamessmith70",
        email: "jamessmith70@example.com",
        password: hashedPassword,
        birthday: "2001-02-09",
        hourlyPay: 21.81,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Williams",
        username: "jameswilliams71",
        email: "jameswilliams71@example.com",
        password: hashedPassword,
        birthday: "2006-11-21",
        hourlyPay: 48.11,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Williams",
        username: "benjaminwilliams72",
        email: "benjaminwilliams72@example.com",
        password: hashedPassword,
        birthday: "2002-08-11",
        hourlyPay: 29.79,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Johnson",
        username: "oliviajohnson73",
        email: "oliviajohnson73@example.com",
        password: hashedPassword,
        birthday: "2001-10-16",
        hourlyPay: 30.12,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Smith",
        username: "noahsmith74",
        email: "noahsmith74@example.com",
        password: hashedPassword,
        birthday: "1990-05-26",
        hourlyPay: 14.46,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Martinez",
        username: "jamesmartinez75",
        email: "jamesmartinez75@example.com",
        password: hashedPassword,
        birthday: "2004-01-11",
        hourlyPay: 15.06,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Miller",
        username: "jamesmiller76",
        email: "jamesmiller76@example.com",
        password: hashedPassword,
        birthday: "2009-02-11",
        hourlyPay: 14.51,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Smith",
        username: "jamessmith77",
        email: "jamessmith77@example.com",
        password: hashedPassword,
        birthday: "2004-03-10",
        hourlyPay: 14.06,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Smith",
        username: "oliviasmith78",
        email: "oliviasmith78@example.com",
        password: hashedPassword,
        birthday: "1997-11-03",
        hourlyPay: 46.01,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Emma",
        surname: "Rodriguez",
        username: "emmarodriguez79",
        email: "emmarodriguez79@example.com",
        password: hashedPassword,
        birthday: "1995-02-21",
        hourlyPay: 39.65,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Rodriguez",
        username: "noahrodriguez80",
        email: "noahrodriguez80@example.com",
        password: hashedPassword,
        birthday: "1995-09-25",
        hourlyPay: 29.06,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Garcia",
        username: "avagarcia81",
        email: "avagarcia81@example.com",
        password: hashedPassword,
        birthday: "1995-03-05",
        hourlyPay: 30.66,
        departmentId: departmentMap["Engineering"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Liam",
        surname: "Jones",
        username: "liamjones82",
        email: "liamjones82@example.com",
        password: hashedPassword,
        birthday: "1995-10-27",
        hourlyPay: 16.52,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Rodriguez",
        username: "noahrodriguez83",
        email: "noahrodriguez83@example.com",
        password: hashedPassword,
        birthday: "2008-02-02",
        hourlyPay: 28.16,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Davis",
        username: "noahdavis84",
        email: "noahdavis84@example.com",
        password: hashedPassword,
        birthday: "1991-08-15",
        hourlyPay: 27.6,
        departmentId: departmentMap["Operations"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ava",
        surname: "Williams",
        username: "avawilliams85",
        email: "avawilliams85@example.com",
        password: hashedPassword,
        birthday: "1993-07-21",
        hourlyPay: 49.31,
        departmentId: departmentMap["Quality Assurance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Williams",
        username: "oliviawilliams86",
        email: "oliviawilliams86@example.com",
        password: hashedPassword,
        birthday: "1995-11-04",
        hourlyPay: 16.65,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Olivia",
        surname: "Williams",
        username: "oliviawilliams87",
        email: "oliviawilliams87@example.com",
        password: hashedPassword,
        birthday: "2004-03-06",
        hourlyPay: 17.72,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Rodriguez",
        username: "williamrodriguez88",
        email: "williamrodriguez88@example.com",
        password: hashedPassword,
        birthday: "2001-02-09",
        hourlyPay: 11.0,
        departmentId: departmentMap["Customer Support"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Brown",
        username: "isabellabrown89",
        email: "isabellabrown89@example.com",
        password: hashedPassword,
        birthday: "1999-05-24",
        hourlyPay: 34.49,
        departmentId: departmentMap["Sales"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Brown",
        username: "sophiabrown90",
        email: "sophiabrown90@example.com",
        password: hashedPassword,
        birthday: "2004-05-16",
        hourlyPay: 15.62,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Williams",
        username: "sophiawilliams91",
        email: "sophiawilliams91@example.com",
        password: hashedPassword,
        birthday: "2002-03-02",
        hourlyPay: 19.54,
        departmentId: departmentMap["Procurement"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Garcia",
        username: "noahgarcia92",
        email: "noahgarcia92@example.com",
        password: hashedPassword,
        birthday: "1990-11-04",
        hourlyPay: 11.73,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Martinez",
        username: "benjaminmartinez93",
        email: "benjaminmartinez93@example.com",
        password: hashedPassword,
        birthday: "1994-07-14",
        hourlyPay: 38.21,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Isabella",
        surname: "Rodriguez",
        username: "isabellarodriguez94",
        email: "isabellarodriguez94@example.com",
        password: hashedPassword,
        birthday: "2007-02-17",
        hourlyPay: 21.02,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Noah",
        surname: "Miller",
        username: "noahmiller95",
        email: "noahmiller95@example.com",
        password: hashedPassword,
        birthday: "1999-10-26",
        hourlyPay: 15.53,
        departmentId: departmentMap["Compliance"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "James",
        surname: "Rodriguez",
        username: "jamesrodriguez96",
        email: "jamesrodriguez96@example.com",
        password: hashedPassword,
        birthday: "2001-12-03",
        hourlyPay: 19.0,
        departmentId: departmentMap["Product"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sophia",
        surname: "Johnson",
        username: "sophiajohnson97",
        email: "sophiajohnson97@example.com",
        password: hashedPassword,
        birthday: "1993-02-16",
        hourlyPay: 26.02,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "William",
        surname: "Rodriguez",
        username: "williamrodriguez98",
        email: "williamrodriguez98@example.com",
        password: hashedPassword,
        birthday: "1997-10-27",
        hourlyPay: 43.91,
        departmentId: departmentMap["Design"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Benjamin",
        surname: "Brown",
        username: "benjaminbrown99",
        email: "benjaminbrown99@example.com",
        password: hashedPassword,
        birthday: "2004-04-04",
        hourlyPay: 26.79,
        departmentId: departmentMap["Legal"],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    console.log("✅ 100 New Users and 10 Departments Added Successfully.");
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete("Users", null, {});
    await queryInterface.bulkDelete("Departments", null, {});
  },
};
